install:
	install -g bin -o root -m 0755 -d $(DATADIR)
	install -g bin -o root -m 0664 13cms.sdr       $(DATADIR)
	install -g bin -o root -m 0664 23cms.sdr       $(DATADIR)
	install -g bin -o root -m 0664 Demo.sdr        $(DATADIR)
	install -g bin -o root -m 0664 SoftRock30.sdr  $(DATADIR)
	install -g bin -o root -m 0664 SoftRock40.sdr  $(DATADIR)
	install -g bin -o root -m 0664 SoftRock80.sdr  $(DATADIR)
	install -g bin -o root -m 0664 SoftRock160.sdr $(DATADIR)
