install:
		install -d -g bin -o root -m 0775 $(DATADIR)
		install -g bin -o root -m 0664 GUISetup.desktop $(DATADIR)
		install -g bin -o root -m 0664 SDRHelp.desktop $(DATADIR)
		install -g bin -o root -m 0664 SDRSetup.desktop $(DATADIR)
		install -g bin -o root -m 0664 UWSDR.desktop $(DATADIR)
		install -g bin -o root -m 0664 GUISetup.png $(DATADIR)
		install -g bin -o root -m 0664 SDRHelp.png $(DATADIR)
		install -g bin -o root -m 0664 SDRSetup.png $(DATADIR)
		install -g bin -o root -m 0664 UWSDR.png $(DATADIR)

