install:
		install -d -g bin -o root -m 0775 $(DATADIR)
		install -d -g bin -o root -m 0775 $(DESKTOPDIR)
		install -d -g bin -o root -m 0775 $(GNOMEPNGDIR)
		install -d -g bin -o root -m 0775 $(KDEPNGDIR)

		install -g bin -o root -m 0664 GUISetup.desktop $(DESKTOPDIR)
		install -g bin -o root -m 0664 SDRHelp.desktop $(DESKTOPDIR)
		install -g bin -o root -m 0664 SDRSetup.desktop $(DESKTOPDIR)

		install -g bin -o root -m 0664 GUISetup.png $(GNOMEPNGDIR)
		install -g bin -o root -m 0664 SDRHelp.png $(GNOMEPNGDIR)
		install -g bin -o root -m 0664 SDRSetup.png $(GNOMEPNGDIR)
		install -g bin -o root -m 0664 UWSDR.png $(GNOMEPNGDIR)

		install -g bin -o root -m 0664 GUISetup.png $(KDEPNGDIR)
		install -g bin -o root -m 0664 SDRHelp.png $(KDEPNGDIR)
		install -g bin -o root -m 0664 SDRSetup.png $(KDEPNGDIR)
		install -g bin -o root -m 0664 UWSDR.png $(KDEPNGDIR)

